[config]
reload_apps = false
set_wallpaper = false

[templates.sway]
input_path = "~/.config/matugen/templates/sway-theme.conf"
output_path = "~/.config/sway/config.d/theme.conf"

[templates.waybar]
input_path = "~/.config/matugen/templates/waybar.css"
output_path = "~/.config/waybar/style.css"

[templates.wofi]
input_path = "~/.config/matugen/templates/wofi.css"
output_path = "~/.config/wofi/style.css"
